(function() {var implementors = {};
implementors["dokan"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"dokan/enum.OperationError.html\" title=\"enum dokan::OperationError\">OperationError</a>","synthetic":false,"types":["dokan::OperationError"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"dokan/enum.FillDataError.html\" title=\"enum dokan::FillDataError\">FillDataError</a>","synthetic":false,"types":["dokan::FillDataError"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"dokan/enum.MountError.html\" title=\"enum dokan::MountError\">MountError</a>","synthetic":false,"types":["dokan::MountError"]}];
implementors["widestring"] = [{"text":"impl&lt;C:&nbsp;<a class=\"trait\" href=\"widestring/trait.UChar.html\" title=\"trait widestring::UChar\">UChar</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"widestring/struct.NulError.html\" title=\"struct widestring::NulError\">NulError</a>&lt;C&gt;","synthetic":false,"types":["widestring::ucstring::NulError"]},{"text":"impl&lt;C:&nbsp;<a class=\"trait\" href=\"widestring/trait.UChar.html\" title=\"trait widestring::UChar\">UChar</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"widestring/struct.MissingNulError.html\" title=\"struct widestring::MissingNulError\">MissingNulError</a>&lt;C&gt;","synthetic":false,"types":["widestring::ucstring::MissingNulError"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"widestring/struct.FromUtf32Error.html\" title=\"struct widestring::FromUtf32Error\">FromUtf32Error</a>","synthetic":false,"types":["widestring::ustring::FromUtf32Error"]}];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()